on: push
name: CI
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lint
      uses: actions-contrib/golangci-lint@v1
      with:
        args: run -E golint -E bodyclose
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: cedrickring/golang-action@1.5.2
      with:
        args: go test -v --cover ./... 
