on: push
name: go-site24x7
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Lint
      uses: actions-contrib/golangci-lint@v1
    - name: Test
      uses: cedrickring/golang-action@1.5.2
      with:
        args: go test --cover ./... 
